Imports System.Data
Imports System.Data.SqlClient
Imports System.Exception
Partial Class Master
    Inherits System.Web.UI.MasterPage

    Protected Sub lnkLogOut_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles lnkLogOut.Click
        Response.Cookies("CokieFrom").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieTo").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieLogin").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokiePwd").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieU_SiteName").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieU_ShortName").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieU_SiteID").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieTo").Expires = DateTime.Now.AddDays(-1)
        FormsAuthentication.SignOut()
        Response.Redirect("~/SignOut.aspx")
    End Sub

    Protected Sub Page_Init(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Init
        Me.ID = "MyMasterPage"
    End Sub

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        currentTime.InnerText = "  " + DateTime.Now.ToString("dd/MM/yyyy") + " - " + DateTime.Now.ToString("T")
        Dim namestring As String
        namestring = LoginName1.Page.User.Identity.Name
        Dim userid As String
        userid = namestring
        Try
            Dim usertype As String
            Dim conn As New SqlConnection
            Dim cmd As New SqlCommand
            Dim dr As SqlDataReader
            conn = New SqlConnection(ConfigurationManager.ConnectionStrings("bic0607TWL").ConnectionString)
            conn.Open()
            cmd = New SqlCommand("select * from twl_login (nolock) twl where twl.aud_status<>'D' and twl.u_id=@uid", conn)
            cmd.Parameters.AddWithValue("@uid", userid)
            dr = cmd.ExecuteReader()
            If dr.HasRows = True Then
                dr.Read()
                usertype = dr("u_type")
            Else

            End If
            dr.Close()
            cmd.Dispose()
            conn.Close()
            If userid.ToUpper() = "81679" Then
                LLHDC.Visible = True
            ElseIf userid.ToLower() = "guest" Then
                fu7.Visible = False
                fu17.Visible = False
                fu8.Visible = False
                fu9.Visible = False
                fu10.Visible = False
                fu11.Visible = False
                fu12.Visible = False
                fu13.Visible = False
                fu14.Visible = False
                fu15.Visible = False
                fu16.Visible = False
            ElseIf userid.ToLower() = "81648" Or userid.ToLower() = "81590" Then
                fu5.Visible = True
                fu5new.Visible = True
                fu5cbk.Visible = True
                fu4.Visible = True
                fu4brnch.Visible = True
                fu4a.Visible = True
                fu6.Visible = True
                fundissued.Visible = True

                fundissued.Visible = True
                lpaynew.Visible = True
                Lpay.Visible = True
                l4c.Visible = True
                pending.Visible = True
                fu9.Visible = True
                lpay1.Visible = True
                fu4.Visible = True
                fu4brnch.Visible = True
                fu4a.Visible = True
                fu3b.Visible = True
                fu5.Visible = True
                fu5new.Visible = True
                fu5cbk.Visible = True
                fu10.Visible = True
                fu11.Visible = True
                'fu12.Visible = True
                fu13.Visible = True
                fu14.Visible = True
                fu15.Visible = True
                fu16.Visible = True
                lpay2.Visible = True

                NorthCollectionRpt.Visible = True
                a7.Visible = True
                br.Visible = True
                a15.Visible = True
                a18.Visible = True
                md1.Visible = True
                md2.Visible = True
                'md3.Visible = True
                md4.Visible = True
                md5.Visible = True
                md6.Visible = True
                mdg.Visible = True
                mdh.Visible = True
                md7.Visible = True
                md8.Visible = True
                md9.Visible = True
                md10.Visible = True
                md11.Visible = True
                md12.Visible = True
                md14.Visible = True
                mdgg.Visible = True
                mdhh.Visible = True
                mde.Visible = True
                mdf.Visible = True
                mdk.Visible = True
                mda.Visible = True
                mdaa.Visible = True
                md15.Visible = True
                md16.Visible = True
                md17.Visible = True
                md18.Visible = True
                md19.Visible = True
                zonaldeduct.Visible = True
                n1.Visible = True
                n2.Visible = True
                n3.Visible = True
                n4.Visible = True
                n9.Visible = True
                n10.Visible = True
                n11.Visible = True
                n12.Visible = True
                n13.Visible = True
                n14.Visible = True
                n15.Visible = True
                n16.Visible = True
                n17.Visible = True
                n18.Visible = True
                n19.Visible = True
                n20.Visible = True
                cf1.Visible = True
                cf2.Visible = True
                cf3.Visible = True
                cf5.Visible = True
                cf6.Visible = True
                it15.Visible = True
                wms1.Visible = True
                circlebooking.Visible = True
                stax.Visible = True
                pre.Visible = True
                pending.Visible = True
                addition.Visible = True
                lhire.Visible = True
                LHIS.Visible = True
                b29.Visible = True
                b292015.Visible = True
                fu1.Visible = True
                fu2.Visible = True
                fu3.Visible = True
                fu4.Visible = True
                fu4brnch.Visible = True
                fu4a.Visible = True
                fu5.Visible = True
                fu5new.Visible = True
                fu5cbk.Visible = True
                fu6.Visible = True

                validate1.Visible = True
                fu10.Visible = True
                fu11.Visible = True
                'fu12.Visible = True
                fu13.Visible = True
                fu14.Visible = True
                fu15.Visible = True
                fu16.Visible = True
                Cntrctdwnload.Visible = True
                Cntrctdwnload2015.Visible = True
                incllh1.Visible = True

            ElseIf userid.ToLower() = "81691" Or userid.ToLower() = "81039" Or userid.ToLower() = "81511" Or userid.ToLower() = "81343" Or userid.ToLower() = "81528" Then
                fundissued.Visible = True
                lpaynew.Visible = True
                Lpay.Visible = True
                l4c.Visible = True
                pending.Visible = True
                fu9.Visible = True
                lpay1.Visible = True
                fu4.Visible = True
                fu4brnch.Visible = True
                fu4a.Visible = True
                fu3b.Visible = True
                fu5.Visible = True
                fu5new.Visible = True
                fu5cbk.Visible = True
                fu10.Visible = True
                fu11.Visible = True
                'fu12.Visible = True
                fu13.Visible = True
                fu14.Visible = True
                fu15.Visible = True
                fu16.Visible = True
                lpay2.Visible = True

                NorthCollectionRpt.Visible = True
                a7.Visible = True
                br.Visible = True
                a15.Visible = True
                a18.Visible = True
                md1.Visible = True
                md2.Visible = True
                'md3.Visible = True
                md4.Visible = True
                md5.Visible = True
                md6.Visible = True
                mdg.Visible = True
                mdh.Visible = True
                md7.Visible = True
                md8.Visible = True
                md9.Visible = True
                md10.Visible = True
                md11.Visible = True
                md12.Visible = True
                md14.Visible = True
                mdgg.Visible = True
                mdhh.Visible = True
                mde.Visible = True
                mdf.Visible = True
                mdk.Visible = True
                mda.Visible = True
                mdaa.Visible = True
                md15.Visible = True
                md16.Visible = True
                md17.Visible = True
                md18.Visible = True
                md19.Visible = True
                zonaldeduct.Visible = True
                n1.Visible = True
                n2.Visible = True
                n3.Visible = True
                n4.Visible = True
                n9.Visible = True
                n10.Visible = True
                n11.Visible = True
                n12.Visible = True
                n13.Visible = True
                n14.Visible = True
                n15.Visible = True
                n16.Visible = True
                n17.Visible = True
                n18.Visible = True
                n19.Visible = True
                n20.Visible = True
                cf1.Visible = True
                cf2.Visible = True
                cf3.Visible = True
                cf5.Visible = True
                cf6.Visible = True
                it15.Visible = True
                wms1.Visible = True
                circlebooking.Visible = True
                stax.Visible = True
                pre.Visible = True
                pending.Visible = True
                addition.Visible = True
                lhire.Visible = True
                LHIS.Visible = True
                b29.Visible = True
                b292015.Visible = True
                fu1.Visible = True
                fu2.Visible = True
                fu3.Visible = True
                fu4.Visible = True
                fu4brnch.Visible = True
                fu4a.Visible = True
                fu5.Visible = True
                fu5new.Visible = True
                fu5cbk.Visible = True
                fu6.Visible = True

                validate1.Visible = True
                fu10.Visible = True
                fu11.Visible = True
                'fu12.Visible = True
                fu13.Visible = True
                fu14.Visible = True
                fu15.Visible = True
                fu16.Visible = True
                Cntrctdwnload.Visible = True
                Cntrctdwnload2015.Visible = True
                incllh1.Visible = True
            ElseIf userid.ToLower() = "81583" Or userid.ToLower() = "81272" Or userid.ToLower() = "81250" Then
                NorthCollectionRpt.Visible = True
                fundissued.Visible = True
                l4c.Visible = True
                a7.Visible = True
                br.Visible = True
                a15.Visible = True
                a18.Visible = True
                md1.Visible = True
                md2.Visible = True
                'md3.Visible = True
                md4.Visible = True
                md5.Visible = True
                md6.Visible = True
                mdg.Visible = True
                mdh.Visible = True
                md7.Visible = True
                md8.Visible = True
                md9.Visible = True
                md10.Visible = True
                md11.Visible = True
                md12.Visible = True
                md14.Visible = True
                mdgg.Visible = True
                mdhh.Visible = True
                mde.Visible = True
                mdf.Visible = True
                mdk.Visible = True
                mda.Visible = True
                mdaa.Visible = True
                md15.Visible = True
                md16.Visible = True
                md17.Visible = True
                md18.Visible = True
                md19.Visible = True
                zonaldeduct.Visible = True
                n1.Visible = True
                n2.Visible = True
                n3.Visible = True
                n4.Visible = True
                n9.Visible = True
                n10.Visible = True
                n11.Visible = True
                n12.Visible = True
                n13.Visible = True
                n14.Visible = True
                n15.Visible = True
                n16.Visible = True
                n17.Visible = True
                n18.Visible = True
                n19.Visible = True
                n20.Visible = True
                cf1.Visible = True
                cf2.Visible = True
                cf3.Visible = True
                cf5.Visible = True
                cf6.Visible = True
                it15.Visible = True
                wms1.Visible = True
                circlebooking.Visible = True
                stax.Visible = True
                pre.Visible = True
                pending.Visible = True
                addition.Visible = True
                lhire.Visible = True
                LHIS.Visible = True
                b29.Visible = True
                b292015.Visible = True
                fu1.Visible = True
                fu2.Visible = True
                fu3.Visible = True
                fu4.Visible = True
                fu4brnch.Visible = True
                fu4a.Visible = True
                fu5.Visible = True
                fu5new.Visible = True
                fu5cbk.Visible = True
                fu6.Visible = True

                validate1.Visible = True
                fu10.Visible = True
                fu11.Visible = True
                'fu12.Visible = True
                fu13.Visible = True
                fu14.Visible = True
                fu15.Visible = True
                fu16.Visible = True
                Cntrctdwnload.Visible = True
                Cntrctdwnload2015.Visible = True
                incllh1.Visible = True



            ElseIf (userid.ToLower() = ("81532")) Or (userid.ToLower() = ("bicho")) Then
                n1.Visible = True
                n2.Visible = True
                n3.Visible = True
                n4.Visible = True
                n9.Visible = True
                n10.Visible = True
                n11.Visible = True
                n12.Visible = True
                n13.Visible = True
                n14.Visible = True
                n15.Visible = True
                n16.Visible = True
                n17.Visible = True
                n18.Visible = True
                n19.Visible = True
                n20.Visible = True
                n21.Visible = True
                northcollection.Visible = True
                NorthCollectionRpt.Visible = True
                cf2.Visible = True
                b29.Visible = True
                b292015.Visible = True
                validate1.Visible = True
                fu1.Visible = True
                fu2.Visible = True
                Cntrctdwnload.Visible = True
                Cntrctdwnload2015.Visible = True
            ElseIf (userid.ToLower() = ("mysore_south")) Or (userid.ToLower() = ("81170")) Or (userid.ToLower() = ("rane_redhills")) Then
                wms1.Visible = True
                wms2.Visible = True
                wms3.Visible = True
                wms4.Visible = True
                wms5.Visible = True
                wms6.Visible = True
                br.Visible = True
                br.Visible = True
            ElseIf (userid.ToLower() = ("81625")) Then
                o1.Visible = True
                o3.Visible = True
                a15.Visible = True
                amar1.Visible = True
                amar2.Visible = True
            ElseIf (userid.ToLower() = ("81087")) Then
                br.Visible = True
                amar1.Visible = True
                o1.Visible = True
                amar2.Visible = True
                a15.Visible = True
                'ElseIf (userid.ToLower() = ("81695")) Then
                '    b3.Visible = True
                'K.VENKATESAN
                'ElseIf (userid.ToLower() = ("81042")) Then
                '    br.Visible = True
                '    amar1.Visible = True
                '    o1.Visible = True
                '    amar2.Visible = True
                '    it10.Visible = True
                '    it19.Visible = True
                '    a20.Visible = True
                '    a21.Visible = True
                '    amar1.Visible = True
                '    amar2.Visible = True
                '    cbz1.Visible = True
                '    'b3.Visible = True
                '    f7.Visible = True
                '    f8.Visible = True
                '    f14.Visible = True
                '    md7.Visible = True
                '    md6.Visible = True
                '    it12.Visible = True
                '    fu11.Visible = True
                '    outbra1.Visible = True

            ElseIf (userid.ToLower() = ("81532")) Then
                northcollection.Visible = True
                NorthCollectionRpt.Visible = True
                cf2.Visible = True
                DH.Visible = True
                b29.Visible = True
                b292015.Visible = True
            ElseIf (userid.ToLower() = ("81255")) Then
                northcollection.Visible = True
                NorthCollectionRpt.Visible = True

                'ElseIf (userid.ToLower() = ("bng_edp")) Then
                '    it9.Visible = True
                '    br.Visible = True
                '    b3.Visible = True
                '    Cntrctdwnload.Visible = True
            ElseIf (userid.ToLower() = ("81241")) Then
                Cntrctdwnload.Visible = True
                Cntrctdwnload2015.Visible = True
            ElseIf (userid.ToLower() = ("81038")) Then
                fu14.Visible = True
                fu3b.Visible = True
                'R.KADIRVEL
                'ElseIf (userid.ToLower() = ("81088")) Then
                '    a20.Visible = True
                '    a21.Visible = True
                '    DH.Visible = True
                '    BLCHN.Visible = True
                '    Cntrctdwnload.Visible = True
                '    Cntrctdwnload2015.Visible = True
                '    b22.Visible = True
                '    b1.Visible = False
                '    'b2.Visible = False
                '    bmod.Visible = False
                '    'b3.Visible = False
                '    contractACC.Visible = False
                '    it19.Visible = True
                '    a20.Visible = True
                '    a21.Visible = True
                '    amar1.Visible = True
                '    amar2.Visible = True
                '    cbz1.Visible = True
                '    b29.Visible = True
                '    b292015.Visible = True
                '    bilstax.Visible = True
            ElseIf (userid.ToLower() = ("81555")) Then
                LVAPPRV.Visible = True
                it19.Visible = True
                a20.Visible = True
                a21.Visible = True
                amar1.Visible = True
                amar2.Visible = True
                cbz1.Visible = True
                b29.Visible = True
                b292015.Visible = True
                bilstax.Visible = True
                BLCHN.Visible = True
                Cntrctdwnload.Visible = True
                Cntrctdwnload2015.Visible = True
                b22.Visible = True
                b1.Visible = False
                'b2.Visible = False
                bmod.Visible = False
                'b3.Visible = False
                contractACC.Visible = False
                it19.Visible = True
                a20.Visible = True
                a21.Visible = True
                amar1.Visible = True
                amar2.Visible = True
                cbz1.Visible = True
                b29.Visible = True
                b292015.Visible = True
                bilstax.Visible = True
                margincln.Visible = False
                custmarg.Visible = False
                b4.Visible = False
                b5.Visible = False
                HyperLink55.Visible = False
                b6.Visible = False
                b7.Visible = False
                b8.Visible = False
                b9.Visible = False
                b10.Visible = False
                Lpayment.Visible = False
                'lpaynew.Visible = False
                'Lpay.Visible = False
                HyperLink19.Visible = False
                HyperLink49.Visible = False
                HyperLink50.Visible = False
                b11.Visible = False
                b12.Visible = False
                HyperLink33.Visible = False
                Rcov12.Visible = False
                uploadCert.Visible = False
                whin.Visible = False
                whout.Visible = False
                whprint.Visible = False
                whdbtbd.Visible = False
                whstock.Visible = False
                wms1.Visible = False
                wms2.Visible = False
                wms3.Visible = False
                wms4.Visible = False
                wms5.Visible = False
                wms6.Visible = False
                b13.Visible = False
                HyperLink12.Visible = False
                b14.Visible = False
                b15.Visible = False
                b16.Visible = False
                b21.Visible = False
                b17.Visible = False
                payadvcuplod.Visible = False
                rcptonac.Visible = False
                rcptadj.Visible = False
                cr.Visible = False
                br.Visible = False
                bnkdslip.Visible = False
                ddcuplod.Visible = False
                ddccr.Visible = False
                ddcbr.Visible = False
                ddcdwnlod.Visible = False
                northcollection.Visible = False
                b28.Visible = False
                b29.Visible = False
                b292015.Visible = True
                fu1.Visible = False
                fu2.Visible = False
                fu3.Visible = False
                fu3a.Visible = False
                fu3b.Visible = False
                fu4.Visible = False
                fu4brnch.Visible = True
                fu4a.Visible = False
                fu5.Visible = False
                fu5new.Visible = False
                fu5cbk.Visible = True
                fu6.Visible = False
                fu7.Visible = False
                fu8.Visible = False
                fu9.Visible = False
                fu10.Visible = False
                fu11.Visible = False
                'fu12.Visible = False
                fu13.Visible = False
                fu14.Visible = False
                fu15.Visible = False
                fu16.Visible = False

            ElseIf (userid.ToLower() = ("81647")) Or (userid.ToLower() = ("81095")) Or (userid.ToLower() = ("81045")) Or (userid.ToLower() = ("81625")) Then
                a7.Visible = True
                a8.Visible = True
                o1.Visible = True
                md6.Visible = True
                md7.Visible = True
                md2.Visible = True
                amar1.Visible = True
                amar2.Visible = True
                a15.Visible = True
                billsum.Visible = True
                outbra1.Visible = True
                bilstax.Visible = True
                Cntrctdwnload.Visible = True
                Cntrctdwnload2015.Visible = True
                circlebooking.Visible = True

            ElseIf (userid.ToLower() = ("81253")) Or (userid.ToLower() = ("81263")) Then
                DH.Visible = True
                it9.Visible = True
                'lpaynew.Visible = True
                'Lpay.Visible = True
                driverbonus.Visible = True
                ' for Delhi hub preprint manifest, freight amount will show in challan and on the base of this they reporting to Chairman.  


            ElseIf (userid.ToLower() = ("51003")) Then
                a15.Visible = True
            ElseIf (userid.ToLower() = ("81035")) Then
                fu11.Visible = True
                tally2.Visible = True
                fundissued.Visible = True
            ElseIf (userid.ToLower() = ("81044")) Or (userid.ToLower() = ("81034")) Then
                'fu12.Visible = True
                NorthCollectionRpt.Visible = True
                a7.Visible = True
                br.Visible = True
                a15.Visible = True
                a18.Visible = True
                md1.Visible = True
                md2.Visible = True
                'md3.Visible = True
                md4.Visible = True
                md5.Visible = True
                md6.Visible = True
                mdg.Visible = True
                mdh.Visible = True
                md7.Visible = True
                md8.Visible = True
                md9.Visible = True
                md10.Visible = True
                md11.Visible = True
                md12.Visible = True
                md14.Visible = True
                mdgg.Visible = True
                mdhh.Visible = True
                mde.Visible = True
                mdf.Visible = True
                mdk.Visible = True
                mda.Visible = True
                mdaa.Visible = True
                md15.Visible = True
                md16.Visible = True
                md17.Visible = True
                md18.Visible = True
                md19.Visible = True
                zonaldeduct.Visible = True
                n1.Visible = True
                n2.Visible = True
                n3.Visible = True
                n4.Visible = True
                n9.Visible = True
                n10.Visible = True
                n11.Visible = True
                n12.Visible = True
                n13.Visible = True
                n14.Visible = True
                n15.Visible = True
                n16.Visible = True
                n17.Visible = True
                n18.Visible = True
                n19.Visible = True
                n20.Visible = True
                cf1.Visible = True
                cf2.Visible = True
                cf3.Visible = True
                cf5.Visible = True
                cf6.Visible = True
                it15.Visible = True
                wms1.Visible = True
                circlebooking.Visible = True
                stax.Visible = True
                pre.Visible = True
                pending.Visible = True
                addition.Visible = True
                lhire.Visible = True
                LHIS.Visible = True
                b29.Visible = True
                b292015.Visible = True
                fu1.Visible = True
                fu2.Visible = True
                fu3.Visible = True
                fu4.Visible = True
                fu4brnch.Visible = True
                fu4a.Visible = True
                fu5.Visible = True
                fu5new.Visible = True
                fu5cbk.Visible = True
                fu6.Visible = True
                validate1.Visible = True
                fu10.Visible = True
                fu11.Visible = True
                'fu12.Visible = True
                fu13.Visible = True
                fu14.Visible = True
                fu15.Visible = True
                fu16.Visible = True
                bilstax.Visible = True
                Cntrctdwnload.Visible = True
                Cntrctdwnload2015.Visible = True
                incllh1.Visible = True


            ElseIf (userid.ToLower() = ("81668")) Or (userid.ToLower() = ("81725")) Then
                b29.Visible = True
                b292015.Visible = True
                validate1.Visible = True
                ' lpaynew.Visible = True
                'Lpay.Visible = True
                pending.Visible = True
                fu9.Visible = True
                lpay1.Visible = True
                fu4.Visible = True
                fu4brnch.Visible = True
                fu4a.Visible = True
                fu5.Visible = True
                fu5new.Visible = True
                fu5cbk.Visible = True
                fu10.Visible = True
                fu11.Visible = True
                'fu12.Visible = True
                fu13.Visible = True
                fu14.Visible = True
                fu15.Visible = True
                lpay2.Visible = True
                recon.Visible = True
            ElseIf (userid.ToLower() = ("pbz")) Or (userid.ToLower() = ("81079")) Or (userid.ToLower() = ("nbz")) Or (userid.ToLower() = ("jbz")) Then
                BLCHN.Visible = True
                Cntrctdwnload.Visible = True
                Cntrctdwnload2015.Visible = True
                b22.Visible = True
                b1.Visible = False
                'b2.Visible = False
                bmod.Visible = False
                'b3.Visible = False
                contractACC.Visible = False
                it19.Visible = True
                a20.Visible = True
                a21.Visible = True
                amar1.Visible = True
                amar2.Visible = True
                cbz1.Visible = True
                b29.Visible = True
                b292015.Visible = True
                bilstax.Visible = True
                margincln.Visible = False
                custmarg.Visible = False
                b4.Visible = False
                b5.Visible = False
                HyperLink55.Visible = False
                b6.Visible = False
                b7.Visible = False
                b8.Visible = False
                b9.Visible = False
                b10.Visible = False
                Lpayment.Visible = False
                'lpaynew.Visible = False
                'Lpay.Visible = False
                HyperLink19.Visible = False
                HyperLink49.Visible = False
                HyperLink50.Visible = False
                b11.Visible = False
                b12.Visible = False
                HyperLink33.Visible = False
                Rcov12.Visible = False
                uploadCert.Visible = False
                whin.Visible = False
                whout.Visible = False
                whprint.Visible = False
                whdbtbd.Visible = False
                whstock.Visible = False
                wms1.Visible = False
                wms2.Visible = False
                wms3.Visible = False
                wms4.Visible = False
                wms5.Visible = False
                wms6.Visible = False
                b13.Visible = False
                HyperLink12.Visible = False
                b14.Visible = False
                b15.Visible = False
                b16.Visible = False
                b21.Visible = False
                b17.Visible = False
                payadvcuplod.Visible = False
                rcptonac.Visible = False
                rcptadj.Visible = False
                cr.Visible = False
                br.Visible = False
                bnkdslip.Visible = False
                ddcuplod.Visible = False
                ddccr.Visible = False
                ddcbr.Visible = False
                ddcdwnlod.Visible = False
                northcollection.Visible = False
                b28.Visible = False
                b29.Visible = False
                b292015.Visible = True
                fu1.Visible = False
                fu2.Visible = False
                fu3.Visible = False
                fu3a.Visible = False
                fu3b.Visible = False
                fu4.Visible = False
                fu4brnch.Visible = True
                fu4a.Visible = False
                fu5.Visible = False
                fu5new.Visible = False
                fu5cbk.Visible = True
                fu6.Visible = False
                fu7.Visible = False
                fu8.Visible = False
                fu9.Visible = False
                fu10.Visible = False
                fu11.Visible = False
                'fu12.Visible = False
                fu13.Visible = False
                fu14.Visible = False
                fu15.Visible = False
                fu16.Visible = False
            ElseIf (userid.ToLower() = ("81040")) Then
                pending.Visible = True

            ElseIf (userid.ToLower() = ("81033")) Then
                LVAPPRV.Visible = True
            ElseIf (userid.ToLower() = ("81080")) Or (userid.ToLower() = ("81091")) Or (userid.ToLower() = ("81037")) Or (userid.ToLower() = ("sarfaraz")) Or (userid.ToLower() = ("51172")) Then
                fundissued.Visible = True
                LVAPPRV.Visible = True
                IT221.Visible = True
                IT222.Visible = True
                IT223.Visible = True
                IT224.Visible = True
                IT225.Visible = True
                IT226.Visible = True
                lpaynew.Visible = True
                Lpay.Visible = True
                fu5new.Visible = True
                fu5cbk.Visible = True
                driverbonus.Visible = True
                Podsubmissionupd.Visible = True
                l4c.Visible = True
                LLHDC.Visible = True
                check1.Visible = True
                check2.Visible = True
                check3.Visible = True
                check4.Visible = True
                check5.Visible = True
                check6.Visible = True
                cancelcr.Visible = True
                cancelbr.Visible = True
                ddcbr.Visible = True
                ddcuplod.Visible = True
                ddcdwnlod.Visible = True
                a20.Visible = True
                a21.Visible = True
                br.Visible = True
                n1.Visible = True
                n2.Visible = True
                n3.Visible = True
                n4.Visible = True
                n5.Visible = True
                n6.Visible = True
                n7.Visible = True
                n8.Visible = True
                n9.Visible = True
                n10.Visible = True
                n11.Visible = True
                n12.Visible = True
                n13.Visible = True
                n14.Visible = True
                n15.Visible = True
                n16.Visible = True
                n17.Visible = True
                n18.Visible = True
                n19.Visible = True
                n20.Visible = True
                n21.Visible = True
                cf1.Visible = True
                cf2.Visible = True
                cf3.Visible = True
                cf5.Visible = True
                cf6.Visible = True
                it0.Visible = True
                it1.Visible = True
                it2.Visible = True
                it3.Visible = True
                it4.Visible = True
                it6.Visible = True
                it6f.Visible = True
                'it6h.Visible = True
                it7.Visible = True
                it8.Visible = True
                it9.Visible = True
                it10.Visible = True
                it11.Visible = True
                it12.Visible = True
                it13.Visible = True
                it14.Visible = True
                'it15.Visible = True
                it16.Visible = True
                it17.Visible = True
                it18.Visible = True
                it19.Visible = True
                it20.Visible = True
                it21.Visible = True
                it22.Visible = True
                it23.Visible = True
                i1.Visible = True
                i2.Visible = True
                w1.Visible = True
                f9.Visible = True
                f10.Visible = True
                f8.Visible = True
                f7.Visible = True
                f6.Visible = True
                f5.Visible = True
                f4.Visible = True
                f3.Visible = True
                f2.Visible = True
                f1.Visible = True
                f14.Visible = True
                F15.Visible = True
                f16.Visible = True
                wms1.Visible = True
                wms2.Visible = True
                wms3.Visible = True
                wms4.Visible = True
                wms5.Visible = True
                wms6.Visible = True
                BLCHN.Visible = True
                'BLCHNTXT.Visible = True
                'BLALL.Visible = True
                'BLALLTXT.Visible = True
                DH.Visible = True
                gatebhupi.Visible = True
                DCWTGP.Visible = True
                cbz1.Visible = True
                o1.Visible = True
                o3.Visible = True
                northcollection.Visible = True
                NorthCollectionRpt.Visible = True
                zonaldeduct.Visible = True
                md1.Visible = True
                md2.Visible = True
                'md3.Visible = True
                md4.Visible = True
                md5.Visible = True
                md6.Visible = True
                mdg.Visible = True
                mdh.Visible = True
                md7.Visible = True
                md8.Visible = True
                md9.Visible = True
                md10.Visible = True
                md11.Visible = True
                md12.Visible = True
                md14.Visible = True
                mdgg.Visible = True
                mdhh.Visible = True
                mde.Visible = True
                mdf.Visible = True
                mdk.Visible = True
                mda.Visible = True
                mdaa.Visible = True
                md15.Visible = True
                md16.Visible = True
                md17.Visible = True
                md18.Visible = True
                md19.Visible = True
                a15.Visible = True
                a18.Visible = True
                a22.Visible = True
                amar1.Visible = True
                b3.Visible = True
                b29.Visible = True
                b292015.Visible = True
                Cntrctdwnload.Visible = True
                Cntrctdwnload2015.Visible = True
                amar2.Visible = True
                circlebooking.Visible = True
                lpaynew.Visible = True
                Lpay.Visible = True
                stax.Visible = True
                lhire.Visible = True
                LHIS.Visible = True
                pre.Visible = True
                pending.Visible = True
                profit.Visible = True
                addition.Visible = True
                broker.Visible = True
                b22.Visible = True
                fu1.Visible = True
                fu2.Visible = True
                fu3.Visible = True
                fu4.Visible = True
                fu4brnch.Visible = True
                fu4a.Visible = True
                fu5.Visible = True
                fu5new.Visible = True
                fu5cbk.Visible = True
                fu6.Visible = True
                b29.Visible = True
                b292015.Visible = True
                validate1.Visible = True
                fu9.Visible = True
                fu10.Visible = True
                fu11.Visible = True
                fu12.Visible = True
                lpay1.Visible = True
                lpay2.Visible = True
                fu13.Visible = True
                fu14.Visible = True
                fu15.Visible = True
                contractACC.Visible = True
                vendor.Visible = True
                tally1.Visible = True
                tally2.Visible = True
                'tally3.Visible = True
                fu16.Visible = True
                outbra1.Visible = True
                recon.Visible = True
                user.Visible = True
                user1.Visible = True
                bilstax.Visible = True
                cngr.Visible = True
                cnch.Visible = True
                cnbill.Visible = True
                cndc.Visible = True
                incllh1.Visible = True
                ' H.ROBIN FERNANDO
                'ElseIf (userid.ToLower() = ("81032")) Then
                '    fundissued.Visible = True
                '    IT221.Visible = True
                '    IT222.Visible = True
                '    IT223.Visible = True
                '    IT224.Visible = True
                '    IT225.Visible = True
                '    IT226.Visible = True
                '    driverbonus.Visible = True
                '    l4c.Visible = True
                '    LLHDC.Visible = True
                '    check1.Visible = True
                '    check2.Visible = True
                '    check3.Visible = True
                '    check4.Visible = True
                '    check5.Visible = True
                '    check6.Visible = True
                '    cancelcr.Visible = True
                '    cancelbr.Visible = True
                '    ddcbr.Visible = True
                '    ddcuplod.Visible = True
                '    ddcdwnlod.Visible = True
                '    a20.Visible = True
                '    a21.Visible = True
                '    br.Visible = True
                '    n1.Visible = True
                '    n2.Visible = True
                '    n3.Visible = True
                '    n4.Visible = True
                '    n5.Visible = True
                '    n6.Visible = True
                '    n7.Visible = True
                '    n8.Visible = True
                '    n9.Visible = True
                '    n10.Visible = True
                '    n11.Visible = True
                '    n12.Visible = True
                '    n13.Visible = True
                '    n14.Visible = True
                '    n15.Visible = True
                '    n16.Visible = True
                '    n17.Visible = True
                '    n18.Visible = True
                '    n19.Visible = True
                '    n20.Visible = True
                '    n21.Visible = True
                '    cf1.Visible = True
                '    cf2.Visible = True
                '    cf3.Visible = True
                '    cf5.Visible = True
                '    cf6.Visible = True
                '    it0.Visible = True
                '    it1.Visible = True
                '    it2.Visible = True
                '    it3.Visible = True
                '    it4.Visible = True
                '    it6.Visible = True
                '    it6f.Visible = True
                '    'it6h.Visible = True
                '    it7.Visible = True
                '    it8.Visible = True
                '    it9.Visible = True
                '    it10.Visible = True
                '    it11.Visible = True
                '    it12.Visible = True
                '    it13.Visible = True
                '    it14.Visible = True
                '    'it15.Visible = True
                '    it16.Visible = True
                '    it17.Visible = True
                '    it18.Visible = True
                '    it19.Visible = True
                '    it20.Visible = True
                '    it21.Visible = True
                '    it22.Visible = True
                '    it23.Visible = True
                '    i1.Visible = True
                '    i2.Visible = True
                '    w1.Visible = True
                '    f9.Visible = True
                '    f10.Visible = True
                '    f8.Visible = True
                '    f7.Visible = True
                '    f6.Visible = True
                '    f5.Visible = True
                '    f4.Visible = True
                '    f3.Visible = True
                '    f2.Visible = True
                '    f1.Visible = True
                '    f14.Visible = True
                '    F15.Visible = True
                '    f16.Visible = True
                '    wms1.Visible = True
                '    wms2.Visible = True
                '    wms3.Visible = True
                '    wms4.Visible = True
                '    wms5.Visible = True
                '    wms6.Visible = True
                '    BLCHN.Visible = True
                '    'BLCHNTXT.Visible = True
                '    'BLALL.Visible = True
                '    'BLALLTXT.Visible = True
                '    DH.Visible = True
                '    gatebhupi.Visible = True
                '    DCWTGP.Visible = True
                '    cbz1.Visible = True
                '    o1.Visible = True
                '    o3.Visible = True
                '    northcollection.Visible = True
                '    NorthCollectionRpt.Visible = True
                '    zonaldeduct.Visible = True
                '    md1.Visible = True
                '    md2.Visible = True
                '    'md3.Visible = True
                '    md4.Visible = True
                '    md5.Visible = True
                '    md6.Visible = True
                '    mdg.Visible = True
                '    mdh.Visible = True
                '    md7.Visible = True
                '    md8.Visible = True
                '    md9.Visible = True
                '    md10.Visible = True
                '    md11.Visible = True
                '    md12.Visible = True
                '    md14.Visible = True
                '    mdgg.Visible = True
                '    mdhh.Visible = True
                '    mde.Visible = True
                '    mdf.Visible = True
                '    mdk.Visible = True
                '    mda.Visible = True
                '    mdaa.Visible = True
                '    md15.Visible = True
                '    md16.Visible = True
                '    md17.Visible = True
                '    md18.Visible = True
                '    md19.Visible = True
                '    a15.Visible = True
                '    a18.Visible = True
                '    a22.Visible = True
                '    amar1.Visible = True
                '    b3.Visible = True
                '    b29.Visible = True
                '    b292015.Visible = True
                '    Cntrctdwnload.Visible = True
                '    Cntrctdwnload2015.Visible = True
                '    amar2.Visible = True
                '    circlebooking.Visible = True
                '    lpaynew.Visible = True
                '    Lpay.Visible = True
                '    stax.Visible = True
                '    lhire.Visible = True
                '    LHIS.Visible = True
                '    pre.Visible = True
                '    pending.Visible = True
                '    profit.Visible = True
                '    addition.Visible = True
                '    broker.Visible = True
                '    b22.Visible = True
                '    fu1.Visible = True
                '    fu2.Visible = True
                '    fu3.Visible = True
                '    fu4.Visible = True
                '    fu4brnch.Visible = True
                '    fu4a.Visible = True
                '    fu5.Visible = True
                '    fu5new.Visible = True
                '    fu5cbk.Visible = True
                '    fu6.Visible = True
                '    b29.Visible = True
                '    b292015.Visible = True
                '    validate1.Visible = True
                '    fu9.Visible = True
                '    fu10.Visible = True
                '    fu11.Visible = True
                '    fu12.Visible = True
                '    lpay1.Visible = True
                '    lpay2.Visible = True
                '    fu13.Visible = True
                '    fu14.Visible = True
                '    fu15.Visible = True
                '    contractACC.Visible = True
                '    vendor.Visible = True
                '    tally1.Visible = True
                '    tally2.Visible = True
                '    'tally3.Visible = True
                '    fu16.Visible = True
                '    outbra1.Visible = True
                '    recon.Visible = True
                '    user.Visible = True
                '    user1.Visible = True
                '    bilstax.Visible = True
                '    cngr.Visible = True
                '    cnch.Visible = True
                '    cnbill.Visible = True
                '    cndc.Visible = True
                '    incllh1.Visible = True


            ElseIf (userid.ToLower() = ("81691")) Or (userid.ToLower() = ("81520")) Or (userid.ToLower() = ("81511")) Or (userid.ToLower() = ("81044")) Or (userid.ToLower() = ("81343")) Or (userid.ToLower() = ("81528")) Or (userid.ToLower() = ("msg")) Then
                NorthCollectionRpt.Visible = True
                a7.Visible = True
                br.Visible = True
                a15.Visible = True
                a18.Visible = True
                md1.Visible = True
                md2.Visible = True
                'md3.Visible = True
                md4.Visible = True
                md5.Visible = True
                md6.Visible = True
                mdg.Visible = True
                mdh.Visible = True
                md7.Visible = True
                md8.Visible = True
                md9.Visible = True
                md10.Visible = True
                md11.Visible = True
                md12.Visible = True
                md14.Visible = True
                mdgg.Visible = True
                mdhh.Visible = True
                mde.Visible = True
                mdf.Visible = True
                mdk.Visible = True
                mda.Visible = True
                mdaa.Visible = True
                md15.Visible = True
                md16.Visible = True
                md17.Visible = True
                md18.Visible = True
                md19.Visible = True
                zonaldeduct.Visible = True
                n1.Visible = True
                n2.Visible = True
                n3.Visible = True
                n4.Visible = True
                n9.Visible = True
                n10.Visible = True
                n11.Visible = True
                n12.Visible = True
                n13.Visible = True
                n14.Visible = True
                n15.Visible = True
                n16.Visible = True
                n17.Visible = True
                n18.Visible = True
                n19.Visible = True
                n20.Visible = True
                cf1.Visible = True
                cf2.Visible = True
                cf3.Visible = True
                cf5.Visible = True
                cf6.Visible = True
                it15.Visible = True
                wms1.Visible = True
                circlebooking.Visible = True
                stax.Visible = True
                pre.Visible = True
                pending.Visible = True
                addition.Visible = True
                lhire.Visible = True
                LHIS.Visible = True
                b29.Visible = True
                b292015.Visible = True
                fu1.Visible = True
                fu2.Visible = True
                fu3.Visible = True
                fu4.Visible = True
                fu4brnch.Visible = True
                fu4a.Visible = True
                fu5.Visible = True
                fu5new.Visible = True
                fu5cbk.Visible = True
                fu6.Visible = True
                validate1.Visible = True
                fu10.Visible = True
                fu11.Visible = True
                'fu12.Visible = True
                fu13.Visible = True
                fu14.Visible = True
                fu15.Visible = True
                fu16.Visible = True
                bilstax.Visible = True
                incllh1.Visible = True

            ElseIf usertype.ToUpper() = "EMPLOYEE" Then

            End If


        Catch ex As Exception

            ''   Response.Write("<script>alert('Error Occurred.');</script>")

            ScriptManager.RegisterStartupScript(Me, Type.GetType("Master"), UniqueID, "alert(""Error Occurred."")", True)

        End Try



        'If (HttpContext.Current.User.Identity.Name.Equals("81679")) Then
        '    LLHDC.Visible = True
        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("gorav_acc")) Then

        '    b1.Visible = False
        '    b2.Visible = False
        '    b4.Visible = False
        '    b5.Visible = False
        '    b6.Visible = False
        '    b7.Visible = False
        '    b8.Visible = False
        '    b9.Visible = False
        '    b10.Visible = False
        '    b11.Visible = False
        '    b12.Visible = False
        '    b13.Visible = False
        '    b14.Visible = False
        '    b15.Visible = False
        '    b16.Visible = False
        '    b17.Visible = False
        '    b21.Visible = False
        '    b24.Visible = False
        '    b25.Visible = False
        '    b26.Visible = False
        '    b27.Visible = False
        '    cr.Visible = False
        '    br.Visible = True
        '    contractACC.Visible = True
        '    Cntrctdwnload.Visible = False

        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81691")) Or (HttpContext.Current.User.Identity.Name.Equals("81583")) Or (HttpContext.Current.User.Identity.Name.Equals("81039")) Or (HttpContext.Current.User.Identity.Name.Equals("81511")) Or (HttpContext.Current.User.Identity.Name.Equals("81044")) Or (HttpContext.Current.User.Identity.Name.Equals("81343")) Or (HttpContext.Current.User.Identity.Name.Equals("81528")) Or (HttpContext.Current.User.Identity.Name.Equals("81034")) Or (HttpContext.Current.User.Identity.Name.Equals("msg")) Then
        '    NorthCollectionRpt.Visible = True
        '    a7.Visible = True
        '    br.Visible = True
        '    a15.Visible = True
        '    a18.Visible = True
        '    md1.Visible = True
        '    md2.Visible = True
        '    md3.Visible = True
        '    md4.Visible = True
        '    md5.Visible = True
        '    md6.Visible = True
        '    mdg.Visible = True
        '    mdh.Visible = True
        '    md7.Visible = True
        '    md8.Visible = True
        '    md9.Visible = True
        '    md10.Visible = True
        '    md11.Visible = True
        '    md12.Visible = True
        '    md14.Visible = True
        '    mdgg.Visible = True
        '    mdhh.Visible = True
        '    mde.Visible = True
        '    mdf.Visible = True
        '    mdk.Visible = True
        '    mda.Visible = True
        '    mdaa.Visible = True
        '    md15.Visible = True
        '    md16.Visible = True
        '    md17.Visible = True
        '    md18.Visible = True
        '    md19.Visible = True
        '    zonaldeduct.Visible = True
        '    n1.Visible = True
        '    n2.Visible = True
        '    n3.Visible = True
        '    n4.Visible = True
        '    n9.Visible = True
        '    n10.Visible = True
        '    n11.Visible = True
        '    n12.Visible = True
        '    n13.Visible = True
        '    n14.Visible = True
        '    n15.Visible = True
        '    n16.Visible = True
        '    n17.Visible = True
        '    n18.Visible = True
        '    n19.Visible = True
        '    n20.Visible = True
        '    cf1.Visible = True
        '    cf2.Visible = True
        '    cf3.Visible = True
        '    cf5.Visible = True
        '    cf6.Visible = True
        '    it15.Visible = True
        '    wms1.Visible = True
        '    circlebooking.Visible = True
        '    stax.Visible = True
        '    pre.Visible = True
        '    pending.Visible = True
        '    addition.Visible = True
        '    lhire.Visible = True
        '    LHIS.Visible = True
        '    b29.Visible = True
        '    fu1.Visible = True
        '    fu2.Visible = True
        '    fu3.Visible = True
        '    fu4.Visible = True
        '    fu4a.Visible = True
        '    fu5.Visible = True
        '    fu6.Visible = True
        '    b29.Visible = True
        '    validate1.Visible = True
        '    fu10.Visible = True
        '    fu11.Visible = True
        '    fu12.Visible = True
        '    fu13.Visible = True
        '    fu14.Visible = True
        '    fu15.Visible = True
        '    fu16.Visible = True
        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("cdb")) Or (HttpContext.Current.User.Identity.Name.Equals("81032")) Or (HttpContext.Current.User.Identity.Name.Equals("ao_it")) Or (HttpContext.Current.User.Identity.Name.Equals("81037")) Or (HttpContext.Current.User.Identity.Name.Equals("sarfaraz")) Or (HttpContext.Current.User.Identity.Name.Equals("81080")) Then
        '    LLHDC.Visible = True
        '    check1.Visible = True
        '    check2.Visible = True
        '    check3.Visible = True
        '    check4.Visible = True
        '    check5.Visible = True
        '    check6.Visible = True
        '    cancelcr.Visible = True
        '    cancelbr.Visible = True
        '    ddcbr.Visible = True
        '    ddcuplod.Visible = True
        '    ddcdwnlod.Visible = True
        '    a20.Visible = True
        '    a21.Visible = True
        '    br.Visible = True
        '    n1.Visible = True
        '    n2.Visible = True
        '    n3.Visible = True
        '    n4.Visible = True
        '    n5.Visible = True
        '    n6.Visible = True
        '    n7.Visible = True
        '    n8.Visible = True
        '    n9.Visible = True
        '    n10.Visible = True
        '    n11.Visible = True
        '    n12.Visible = True
        '    n13.Visible = True
        '    n14.Visible = True
        '    n15.Visible = True
        '    n16.Visible = True
        '    n17.Visible = True
        '    n18.Visible = True
        '    n19.Visible = True
        '    n20.Visible = True
        '    n21.Visible = True
        '    cf1.Visible = True
        '    cf2.Visible = True
        '    cf3.Visible = True
        '    cf5.Visible = True
        '    cf6.Visible = True
        '    it0.Visible = True
        '    it1.Visible = True
        '    it2.Visible = True
        '    it3.Visible = True
        '    it4.Visible = True
        '    it6.Visible = True
        '    it7.Visible = True
        '    it8.Visible = True
        '    it9.Visible = True
        '    it10.Visible = True
        '    it11.Visible = True
        '    it12.Visible = True
        '    it13.Visible = True
        '    it14.Visible = True
        '    it15.Visible = True
        '    it16.Visible = True
        '    it17.Visible = True
        '    it18.Visible = True
        '    it19.Visible = True
        '    it20.Visible = True
        '    it21.Visible = True
        '    it22.Visible = True
        '    it23.Visible = True
        '    i1.Visible = True
        '    i2.Visible = True
        '    w1.Visible = True
        '    f9.Visible = True
        '    f10.Visible = True
        '    f8.Visible = True
        '    f7.Visible = True
        '    f6.Visible = True
        '    f5.Visible = True
        '    f4.Visible = True
        '    f3.Visible = True
        '    f2.Visible = True
        '    f1.Visible = True
        '    f14.Visible = True
        '    F15.Visible = True
        '    f16.Visible = True
        '    wms1.Visible = True
        '    wms2.Visible = True
        '    wms3.Visible = True
        '    wms4.Visible = True
        '    wms5.Visible = True
        '    wms6.Visible = True
        '    BLCHN.Visible = True
        '    'BLCHNTXT.Visible = True
        '    'BLALL.Visible = True
        '    'BLALLTXT.Visible = True
        '    DH.Visible = True
        '    gatebhupi.Visible = True
        '    DCWTGP.Visible = True
        '    cbz1.Visible = True
        '    o1.Visible = True
        '    o3.Visible = True
        '    northcollection.Visible = True
        '    NorthCollectionRpt.Visible = True
        '    zonaldeduct.Visible = True
        '    md1.Visible = True
        '    md2.Visible = True
        '    md3.Visible = True
        '    md4.Visible = True
        '    md5.Visible = True
        '    md6.Visible = True
        '    mdg.Visible = True
        '    mdh.Visible = True
        '    md7.Visible = True
        '    md8.Visible = True
        '    md9.Visible = True
        '    md10.Visible = True
        '    md11.Visible = True
        '    md12.Visible = True
        '    md14.Visible = True
        '    mdgg.Visible = True
        '    mdhh.Visible = True
        '    mde.Visible = True
        '    mdf.Visible = True
        '    mdk.Visible = True
        '    mda.Visible = True
        '    mdaa.Visible = True
        '    md15.Visible = True
        '    md16.Visible = True
        '    md17.Visible = True
        '    md18.Visible = True
        '    md19.Visible = True
        '    a15.Visible = True
        '    a18.Visible = True
        '    a22.Visible = True
        '    amar1.Visible = True
        '    b3.Visible = True
        '    b29.Visible = True
        '    Cntrctdwnload.Visible = True
        '    amar2.Visible = True
        '    circlebooking.Visible = True
        '    lpaynew.Visible = True
        '   Lpay.Visible = True
        '    stax.Visible = True
        '    lhire.Visible = True
        '    LHIS.Visible = True
        '    pre.Visible = True
        '    pending.Visible = True
        '    profit.Visible = True
        '    addition.Visible = True
        '    broker.Visible = True
        '    b22.Visible = True
        '    fu1.Visible = True
        '    fu2.Visible = True
        '    fu3.Visible = True
        '    fu4.Visible = True
        '    fu4a.Visible = True
        '    fu5.Visible = True
        '    fu6.Visible = True
        '    b29.Visible = True
        '    validate1.Visible = True
        '    fu9.Visible = True
        '    fu10.Visible = True
        '    fu11.Visible = True
        '    fu12.Visible = True
        '    lpay1.Visible = True
        '    lpay2.Visible = True
        '    fu13.Visible = True
        '    fu14.Visible = True
        '    fu15.Visible = True
        '    contractACC.Visible = True
        '    vendor.Visible = True
        '    tally1.Visible = True
        '    fu16.Visible = True
        '    outbra1.Visible = True
        '    recon.Visible = True

        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("sarfaraz")) Or (HttpContext.Current.User.Identity.Name.Equals("81532")) Or (HttpContext.Current.User.Identity.Name.Equals("bicho")) Or (HttpContext.Current.User.Identity.Name.Equals("81037")) Or (HttpContext.Current.User.Identity.Name.Equals("81032")) Or (HttpContext.Current.User.Identity.Name.Equals("81583")) Then
        '    n1.Visible = True
        '    n2.Visible = True
        '    n3.Visible = True
        '    n4.Visible = True
        '    n9.Visible = True
        '    n10.Visible = True
        '    n11.Visible = True
        '    n12.Visible = True
        '    n13.Visible = True
        '    n14.Visible = True
        '    n15.Visible = True
        '    n16.Visible = True
        '    n17.Visible = True
        '    n18.Visible = True
        '    n19.Visible = True
        '    n20.Visible = True
        '    n21.Visible = True
        '    northcollection.Visible = True
        '    NorthCollectionRpt.Visible = True
        '    cf2.Visible = True
        '    b29.Visible = True
        '    validate1.Visible = True
        '    fu1.Visible = True
        '    fu2.Visible = True
        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("mysore_south")) Or (HttpContext.Current.User.Identity.Name.Equals("81170")) Or (HttpContext.Current.User.Identity.Name.Equals("rane_redhills")) Then
        '    wms1.Visible = True
        '    wms2.Visible = True
        '    wms3.Visible = True
        '    wms4.Visible = True
        '    wms5.Visible = True
        '    wms6.Visible = True
        '    br.Visible = True
        '    br.Visible = True
        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81625")) Then
        '    o1.Visible = True
        '    o3.Visible = True
        '    a15.Visible = True
        '    amar1.Visible = True
        '    amar2.Visible = True
        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81087")) Then
        '    br.Visible = True
        '    amar1.Visible = True
        '    o1.Visible = True
        '    amar2.Visible = True
        '    a15.Visible = True

        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81042")) Then
        '    br.Visible = True
        '    amar1.Visible = True
        '    o1.Visible = True
        '    amar2.Visible = True
        '    it10.Visible = True
        '    it19.Visible = True
        '    a20.Visible = True
        '    a21.Visible = True
        '    amar1.Visible = True
        '    amar2.Visible = True
        '    cbz1.Visible = True
        '    b3.Visible = True
        '    f7.Visible = True
        '    f8.Visible = True
        '    f14.Visible = True
        '    md7.Visible = True
        '    md6.Visible = True
        '    it12.Visible = True
        '    fu11.Visible = True
        '    outbra1.Visible = True

        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81532")) Then
        '    northcollection.Visible = True
        '    NorthCollectionRpt.Visible = True
        '    cf2.Visible = True
        '    DH.Visible = True
        '    b29.Visible = True

        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81255")) Then
        '    northcollection.Visible = True
        '    NorthCollectionRpt.Visible = True

        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("bng_edp")) Then
        '    it9.Visible = True
        '    br.Visible = True
        '    b3.Visible = True

        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81038")) Then
        '    fu14.Visible = True
        '    fu3b.Visible = True
        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81088")) Then
        '    a20.Visible = True
        '    a21.Visible = True
        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81079")) Or (HttpContext.Current.User.Identity.Name.Equals("81555")) Then
        '    it19.Visible = True
        '    a20.Visible = True
        '    a21.Visible = True
        '    amar1.Visible = True
        '    amar2.Visible = True
        '    cbz1.Visible = True
        '    b29.Visible = True
        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81647")) Or (HttpContext.Current.User.Identity.Name.Equals("81095")) Or (HttpContext.Current.User.Identity.Name.Equals("81045")) Or (HttpContext.Current.User.Identity.Name.Equals("81625")) Then
        '    a7.Visible = True
        '    a8.Visible = True
        '    o1.Visible = True
        '    md6.Visible = True
        '    md7.Visible = True
        '    amar1.Visible = True
        '    amar2.Visible = True
        '    a15.Visible = True
        '    billsum.Visible = True
        '    outbra1.Visible = True

        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81469")) Or (HttpContext.Current.User.Identity.Name.Equals("81263")) Then
        '    DH.Visible = True
        '    it9.Visible = True
        '    lpaynew.Visible = True
        '   Lpay.Visible = True
        '    ' for Delhi hub preprint manifest, freight amount will show in challan and on the base of this they reporting to Chairman.  
        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81032")) Then
        '    BLCHN.Visible = True
        '    b22.Visible = True
        '    a20.Visible = True
        '    a21.Visible = True
        '    cbz1.Visible = True
        '    it10.Visible = True
        '    it19.Visible = True

        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("51003")) Then
        '    a15.Visible = True
        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81035")) Then
        '    fu11.Visible = True

        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81668")) Or (HttpContext.Current.User.Identity.Name.Equals("81676")) Then
        '    b29.Visible = True
        '    validate1.Visible = True
        '    lpaynew.Visible = True
        '    Lpay.Visible = True
        '    pending.Visible = True
        '    fu9.Visible = True
        '    lpay1.Visible = True
        '    fu4.Visible = True
        '    fu4a.Visible = True
        '    fu5.Visible = True
        '    fu10.Visible = True
        '    fu11.Visible = True
        '    fu12.Visible = True
        '    fu13.Visible = True
        '    fu14.Visible = True
        '    fu15.Visible = True
        '    lpay2.Visible = True
        '    recon.Visible = True
        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("pbz")) Or (HttpContext.Current.User.Identity.Name.Equals("cbz")) Or (HttpContext.Current.User.Identity.Name.Equals("nbz")) Or (HttpContext.Current.User.Identity.Name.Equals("jbz")) Then
        '    BLCHN.Visible = True
        '    b22.Visible = True
        '    b1.Visible = False
        '    b2.Visible = False
        '    bmod.Visible = False
        '    b3.Visible = False
        '    customerentry.Visible = False
        '    contractACC.Visible = False
        '    margincln.Visible = False
        '    custmarg.Visible = False
        '    b4.Visible = False
        '    b5.Visible = False
        '    HyperLink55.Visible = False
        '    b6.Visible = False
        '    b7.Visible = False
        '    b8.Visible = False
        '    b9.Visible = False
        '    b10.Visible = False
        '    Lpayment.Visible = False
        '    lpaynew.Visible = False
        'Lpay.Visible = True
        '    HyperLink19.Visible = False
        '    HyperLink49.Visible = False
        '    HyperLink50.Visible = False
        '    b11.Visible = False
        '    b12.Visible = False
        '    HyperLink33.Visible = False
        '    Rcov12.Visible = False
        '    uploadCert.Visible = False
        '    whin.Visible = False
        '    whout.Visible = False
        '    whprint.Visible = False
        '    whdbtbd.Visible = False
        '    whstock.Visible = False
        '    wms1.Visible = False
        '    wms2.Visible = False
        '    wms3.Visible = False
        '    wms4.Visible = False
        '    wms5.Visible = False
        '    wms6.Visible = False
        '    b13.Visible = False
        '    HyperLink12.Visible = False
        '    b14.Visible = False
        '    b15.Visible = False
        '    b16.Visible = False
        '    b21.Visible = False
        '    b17.Visible = False
        '    payadvcuplod.Visible = False
        '    rcptonac.Visible = False
        '    rcptadj.Visible = False
        '    cr.Visible = False
        '    br.Visible = False
        '    bnkdslip.Visible = False
        '    ddcuplod.Visible = False
        '    ddccr.Visible = False
        '    ddcbr.Visible = False
        '    ddcdwnlod.Visible = False
        '    northcollection.Visible = False
        '    b28.Visible = False
        '    b29.Visible = False
        '    fu1.Visible = False
        '    fu2.Visible = False
        '    fu3.Visible = False
        '    fu3a.Visible = False
        '    fu3b.Visible = False
        '    fu4.Visible = False
        '    fu4a.Visible = False
        '    fu5.Visible = False
        '    fu6.Visible = False
        '    fu7.Visible = False
        '    fu8.Visible = False
        '    fu9.Visible = False
        '    fu10.Visible = False
        '    fu11.Visible = False
        '    fu12.Visible = False
        '    fu13.Visible = False
        '    fu14.Visible = False
        '    fu15.Visible = False
        '    fu16.Visible = False

        'ElseIf (HttpContext.Current.User.Identity.Name.Equals("81090")) Or (HttpContext.Current.User.Identity.Name.Equals("81040")) Then
        '    lpaynew.Visible = True
        'Lpay.Visible = True
        '    pending.Visible = True
        '    fu9.Visible = True
        '    lpay1.Visible = True
        '    fu4.Visible = True
        '    fu4a.Visible = True
        '    fu3b.Visible = True
        '    fu5.Visible = True
        '    fu10.Visible = True
        '    fu11.Visible = True
        '    fu12.Visible = True
        '    fu13.Visible = True
        '    fu14.Visible = True
        '    fu15.Visible = True
        '    fu16.Visible = True
        '    lpay2.Visible = True

        'End If
    End Sub

    Protected Sub ScriptManager1_AsyncPostBackError(ByVal sender As Object, ByVal e As System.Web.UI.AsyncPostBackErrorEventArgs) Handles ScriptManager1.AsyncPostBackError
        ScriptManager1.AsyncPostBackErrorMessage = e.Exception.Message & e.Exception.StackTrace
    End Sub

    Protected Sub LogOutMenu_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles LogOutMenu.Click
        Response.Cookies("CokieFrom").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieTo").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieLogin").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokiePwd").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieU_SiteName").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieU_ShortName").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieU_SiteID").Expires = System.DateTime.Now.AddDays(-1)
        Response.Cookies("CokieTo").Expires = DateTime.Now.AddDays(-1)
        FormsAuthentication.SignOut()
        Response.Redirect("~/SignOut.aspx")
    End Sub
End Class